FROM ubuntu:14.04
RUN apt-get -y update && apt-get -y install curl
RUN useradd -ms /bin/bash testuser && adduser testuser sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER testuser
WORKDIR /home/testuser
