#!/usr/bin/env bash
set -euo pipefail

export PATH="${HOME}/.nix-profile/bin:${PATH}"

dotfiles/apply docker

mkdir -p src/github.com/pseudomuto && cd src/github.com/pseudomuto
git clone https://github.com/pseudomuto/convr.git
git clone https://github.com/pseudomuto/pseudocms.git

cd convr
source ~/.bashrc
exec "$@"
