#!/usr/bin/env bash
set -euo pipefail

NIX_DISTRO="https://releases.nixos.org/nix/nix-2.6.1/install"
HM_RELEASE="release-21.11"

main() {
  install_nix
  install_home_manager
}

install_nix() {
  sh <(curl -L "${NIX_DISTRO}")
}

install_home_manager() {
  if [ -f "${HOME}/.nix-profile/etc/profile.d/nix.sh" ]; then
    source "${HOME}/.nix-profile/etc/profile.d/nix.sh"
    export PATH="${HOME}/.nix-profile/bin:${PATH}"
  fi

  nix-channel --add https://github.com/nix-community/home-manager/archive/${HM_RELEASE}.tar.gz home-manager
  nix-channel --update

  export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}
  nix-shell '<home-manager>' -A install
}

main "$@"
