#!/bin/bash
set -euo pipefail

export PATH="/usr/local/opt/ruby/bin:$PATH"

install_brew() {
 if which brew >/dev/null; then return; fi

 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
}

install_ruby() {
  brew install ruby
  ruby -v
}

main() {
  install_brew
  install_ruby
}

main "$@"
