#!/bin/bash
set -euo pipefail

install_brew() {
 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
}

install_ruby() {
  brew install ruby
  ruby -v
}

find_brew_prefix() {
  local prefix="/usr/local"
  if [ -d /opt/homebrew ]; then prefix="/opt/homebrew"; fi

  echo -n $prefix
}

main() {
  install_brew

  local prefix=$(find_brew_prefix)
  PATH="${prefix}/bin:${prefix}/opt/ruby/bin:${PATH}" install_ruby
}

main "$@"
