#!/bin/bash
set -euo pipefail

usage() {
  echo "  Usage: $0 chruby -v <version>"
}

parse_args() {
  while getopts ":v:" opt; do
    case $opt in
      v) version=${OPTARG};;
      \?) invalid_args;;
    esac
  done
}

met() {
  [[ "$(which chruby-exec && chruby-exec --version)" =~ "chruby version ${version}" ]]
}

meet() {
  download_file "https://github.com/postmodern/chruby/archive/v${version}.tar.gz" /tmp || return $?
  extract_archive "/tmp/v${version}.tar.gz" || return $?

  pushd /tmp/chruby-${version} >/dev/null
  sudo scripts/setup.sh || return $?
  popd >/dev/null

  rm -rf /tmp/v${version}.tar.gz /tmp/chruby-${version}
}
