#!/bin/bash
set -euo pipefail

usage() {
  echo "  Usage: $0 git -v <version>"
}

parse_args() {
  while getopts ":v:" opt; do
    case $opt in
      v) version=${OPTARG};;
      \?) invalid_args;;
    esac
  done
}

met() {
  [[ "$(which git && git --version)" =~ "git version ${version}" ]]
}

meet() {
  install_packages libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev

  download_file "https://github.com/git/git/archive/v${version}.tar.gz" /tmp || return $?
  extract_archive "/tmp/v${version}.tar.gz" || return $?

  pushd /tmp/git-${version} >/dev/null
  make configure || return $?
  ./configure --prefix=/usr/local || return $?
  make all || return $?
  sudo make install || return $?
  popd >/dev/null

  rm -rf /tmp/v${version}.tar.gz /tmp/git-${version}
}
