#!/bin/bash
set -euo pipefail

USER_RUBIES="${HOME}/.rubies"

usage() {
  echo "  Usage: $0 ruby -v <version> [-s]"
}

parse_args() {
  while getopts ":v:s" opt; do
    case $opt in
      v) version=${OPTARG};;
      s) system=1;;
      \?) invalid_args;;
    esac
  done
}

is_system() {
  [[ -n "${system+x}" ]]
}

met() {
  if is_system; then
    [[ "$(which ruby && ruby -v)" =~ "ruby ${version}" ]]
  else
    [[ -d "${USER_RUBIES}/ruby-${version}" ]]
  fi
}

meet() {
  if is_system; then
    sudo ${HOME}/bin/install_ruby --system ruby "${version}"
  else
    ${HOME}/bin/install_ruby ruby "${version}"
  fi
}

