#!/bin/bash
set -euo pipefail

usage() {
  echo "  Usage: $0 ruby-install -v <version>"
}

parse_args() {
  while getopts ":v:" opt; do
    case $opt in
      v) version=${OPTARG};;
      \?) invalid_args;;
    esac
  done
}

met() {
  [[ "$(which ruby-install && ruby-install -V)" =~ "ruby-install: ${version}" ]]
}

meet() {
  download_file "https://github.com/postmodern/ruby-install/archive/v${version}.tar.gz" /tmp || return $?
  extract_archive "/tmp/v${version}.tar.gz" || return $?

  pushd /tmp/ruby-install-${version} >/dev/null
  sudo make install
  popd >/dev/null

  rm -rf /tmp/v${version}.tar.gz /tmp/ruby-install-${version}
}
