# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Personalization
unbind = SUPER ALT, RETURN   # tmux
unbind = SUPER SHIFT, C      # calendar
unbind = SUPER SHIFT, E      # email
unbind = SUPER SHIFT, G      # signal
unbind = SUPER SHIFT, W      # typora
unbind = SUPER SHIFT, Y      # YouTube
unbind = SUPER SHIFT ALT, A  # grok
unbind = SUPER SHIFT ALT, G  # WhatsApp
unbind = SUPER SHIFT ALT, X  # X Post
unbind = SUPER SHIFT CTRL, G # Google Messages

bindd = ALT, SPACE, Scratchpad, togglespecialworkspace, scratchpad
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-or-focus-webapp "Google Calendar" "https://calendar.google.com/calendar/u/0/r/week"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-or-focus-webapp "Gmail" "https://mail.google.com/mail/u/0"
bindd = SUPER SHIFT, T, Tasks, exec, omarchy-launch-or-focus-webapp "AnyList" "https://www.anylist.com/web"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-webapp "YouTube" "https://youtube.com/"
