#!/usr/bin/env ruby
# frozen_string_literal: true

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require "bundler/setup"
require "dotfiles"

exit(Dotfiles::ErrorHandler.call do
  Dotfiles::EntryPoint.call(ARGV.dup)
end)
