#!/usr/bin/env ruby
# frozen_string_literal: true

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require "bundler/inline"
# to be kept up to date with runtime dependencies from gemspec
gemfile do
  source("https://rubygems.org")
  gemspec
end

require "dotfiles"
exit(Dotfiles::ErrorHandler.call { Dotfiles::EntryPoint.call(ARGV.dup) })
