version: "3"

vars:
  BIN_DIR:
    sh: echo "${HOME}/bin"
  TMP_DIR: /tmp/dotfiles

  REJSON_VERSION: 0.5.2

tasks:
  default:
    cmds:
      - task: gvm:install
      - task: rejson:install

  gvm:install:
    desc: Installs GVM (https://github.com/moovweb/gvm)
    internal: true
    silent: true
    env:
      GVM_NO_GIT_BAK: true
      GVM_NO_UPDATE_PROFILE: true
    status:
      - test -d ~/.gvm
    cmds:
      - echo "Installing gvm"
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)"

  rejson:install:
    summary: Install Rejson {{.REJSON_VERSION}}
    internal: true
    silent: true
    status:
      - test -f {{.BIN_DIR}}/ejson
      - "{{.BIN_DIR}}/rejson --version | grep {{.REJSON_VERSION}}"
    cmds:
      - defer: rm -rf {{.TMP_DIR}}/ejson_tmp
      - echo "Installing rejson"
      - mkdir -p {{.TMP_DIR}}/ejson_tmp
      - curl -fsSL -o {{.TMP_DIR}}/ejson_tmp/ejson.tar.gz https://github.com/pseudomuto/rejson/releases/download/v{{.REJSON_VERSION}}/rejson_{{.REJSON_VERSION}}_darwin_arm64.tar.gz
      - tar -xzf {{.TMP_DIR}}/ejson_tmp/ejson.tar.gz -C {{.TMP_DIR}}/ejson_tmp
      - mv {{.TMP_DIR}}/ejson_tmp/rejson {{.BIN_DIR}}/
      - ln -sf {{.BIN_DIR}}/rejson {{.BIN_DIR}}/ejson
